Done with secrets deployment

diff --git a/deploy-secrets b/deploy-secrets
--- a/deploy-secrets
+++ b/deploy-secrets
@@ -1,7 +1,33 @@
 #!/bin/bash
 
-if [ "$1" != "dev" ] && [ "$1" != "production" ]; then
-    exit 'Invalid environment'
+# detect environment
+if [ ! -f '.env' ]; then
+    echo 'No environment file'
+    exit 1
 fi
 
-echo "secrets-$1/projects/magalnick/random-stuff-php/.env.secrets"
+ENVIRONMENT=$(<.env)
+if [ "$ENVIRONMENT" != "dev" ] && [ "$ENVIRONMENT" != "qa" ] && [ "$ENVIRONMENT" != "production" ]; then
+    echo 'Invalid environment'
+    exit 1
+fi
+
+# set git branch based on environment
+# default will be develop for dev or qa, only change for production
+# however if dev or qa, also allow an override to be sent as a command line argument
+GIT_BRANCH='develop'
+if [ "$ENVIRONMENT" == "production" ]; then
+    GIT_BRANCH='master'
+fi
+
+if [ $1 ] && [ "$ENVIRONMENT" != "production" ]; then
+    GIT_BRANCH=$1
+fi
+
+# the actual running of the command doesn't like the '|' or '>' characters in the middle,
+# so breaking it up into multiple commands
+CMD1="git archive --format=tar --remote=ssh://git@gitlab.com/magalnick/secrets-$ENVIRONMENT.git $GIT_BRANCH:projects/magalnick/random-stuff-php -- .env.secrets"
+CMD2="tar xf -"
+CMD3=".env.secrets"
+echo "$CMD1 | $CMD2 > $CMD3"
+`$CMD1 | $CMD2 > $CMD3`
